# -*- coding: utf-8 -*-
"""webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MebNKYIgSXuXmPn0MtcoLiTPcwYPzwba
"""

pip install bs4

pip install requests

import bs4
from bs4 import BeautifulSoup
import requests

url = ('https://www.amazon.in/Apple-iPhone-13-128GB-Blue/dp/B09G9BL5CP?th=1')

headers = {
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
}

r = requests.get(url, {'headers':headers})

soup = bs4.BeautifulSoup(r.text, 'html.parser')

soup.find_all()

soup.find_all('div')

import requests
from bs4 import BeautifulSoup

url = 'https://www.amazon.in/Apple-iPhone-13-128GB-Blue/dp/B09G9BL5CP?th=1'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    'Accept-Encoding': 'gzip, deflate, br',
    'Referer': 'https://www.amazon.in/'
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

reviews = soup.find_all('div', {'data-hook': 'review'})

for review in reviews:
    profile_name = review.find('span', {'class': 'a-profile-name'})
    if profile_name:
        print(profile_name.text)

#response = requests.get(url, headers=headers)
#soup = BeautifulSoup(response.content, 'html.parser')
review_para = soup.find_all('div', {'data-hook': 'review-collapsed'})
review_para_list = []
for review in review_para:
    profile_reviews = review.find_all('span')
    for i in profile_reviews:
        review_para_list.append(i)
        print(i.text)

rating = soup.find_all('i', {'data-hook': 'review-star-rating'})
ratings_list = []
for i in rating:
    profile_rating = i.find_all('span', {'class':'a-icon-alt'})
    for i in profile_rating:
         ratings_list.append(i)
         print(i.text)